[project]
name = "klokah-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scrapy>=2.12.0",
    "twisted>=24.11.0",
    "xmltodict>=0.14.2",
]
